spring.application.name=IM-PT
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
server.port=8080

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.data.redis.host=
spring.data.redis.port=12130
spring.data.redis.password=

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


