spring.application.name=IM-PT


spring.datasource.url=jdbc:mysql://mysql-c104f2e-dineshbelhekar111-1cb5.l.aivencloud.com:28380/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_nzwQSYXQ0i4bPbQRqKh


spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
server.port=8080
